const constants = {
    APP_GET_DATA: 'APP_GET_DATA',
    APP_LOADING: 'APP_LOADING',
    APP_ERROR: 'APP_ERROR',

    COIN_SET_VALUE: 'COIN_SET_VALUE',
    COINS_LIST_FETCH_DATA: 'COINS_LIST_FETCH_DATA',
    COINS_LIST_FETCH_DATA_SUCCESS: 'COINS_LIST_FETCH_DATA_SUCCESS',
    COINS_LIST_LOADING: 'COINS_LIST_LOADING',
    COINS_LIST_ERROR: 'COINS_LIST_ERROR',
    COINS_SELECT_SET_VALUE: 'COINS_SELECT_SET_VALUE',

    CURRENCY_SET_VALUE: 'CURRENCY_SET_VALUE',
    CURRENCIES_LIST_FETCH_DATA: 'CURRENCIES_LIST_FETCH_DATA',
    CURRENCIES_LIST_FETCH_DATA_SUCCESS: 'CURRENCIES_LIST_FETCH_DATA_SUCCESS',
    CURRENCIES_LIST_LOADING: 'CURRENCIES_LIST_LOADING',
    CURRENCIES_LIST_ERROR: 'CURRENCIES_LIST_ERROR',

    MARKET_FETCH_DATA: 'MARKET_FETCH_DATA',
    MARKET_FETCH_DATA_SUCCESS: 'MARKET_FETCH_DATA_SUCCESS',
    MARKET_LOADING: 'MARKET_LOADING',
    MARKET_ERROR: 'MARKET_ERROR',

    SPREADSHEET_SET_LINK: 'SPREADSHEET_SET_LINK',
    SPREADSHEET_SET_DEMO: 'SPREADSHEET_SET_DEMO',
    SPREADSHEET_FETCH_DATA: 'SPREADSHEET_FETCH_DATA',
    SPREADSHEET_FETCH_DATA_SUCCESS: 'SPREADSHEET_FETCH_DATA_SUCCESS',
    SPREADSHEET_LOADING: 'SPREADSHEET_LOADING',
    SPREADSHEET_ERROR: 'SPREADSHEET_ERROR',

    TABLE_SET_DATA: 'TABLE_SET_DATA',
    TABLE_LOADING: 'TABLE_LOADING',
    TABLE_SET_SORT: 'TABLE_SET_SORT',
    TABLE_SET_SORT_CLEAR: 'TABLE_SET_SORT_CLEAR',
    TABLE_GROUP_OPEN: 'TABLE_GROUP_OPEN',
    TABLE_GROUP_OPEN_ALL: 'TABLE_GROUP_OPEN_ALL',
    TABLE_GROUP_OPEN_CLEAR: 'TABLE_GROUP_OPEN_CLEAR',
    TABLE_COLUMNS_HIDDEN: 'TABLE_COLUMNS_HIDDEN'
};

export default constants;
